version: '3.8'

services:
  discord-bot-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: phishing-detection-bot-dev
    restart: "no"  # Don't restart automatically in dev
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DEV=${DEV}
      - PYTHONPATH=/app:/app/src
    volumes:
      # Mount source code for live reloading (development only)
      - ./src:/app/src:ro
      - ./main.py:/app/main.py:ro
      - ./guild_config.py:/app/guild_config.py:ro
      # Persistent data
      - ./data:/app/data
      - ./guild_config.db:/app/guild_config.db
      # Logs
      - ./logs:/app/logs
    networks:
      - bot-network-dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Override command for development (optional)
    # command: ["python", "-u", "main.py"]
    stdin_open: true
    tty: true

networks:
  bot-network-dev:
    driver: bridge
